export const MOCK_QUESTIONS = {
    react: [
        // Easy
        { question: "What is React and why would you use it?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Explain JSX.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are React components?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Difference between functional and class components?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is state in React?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are props in React?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How do you handle events in React?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        // Medium
        { question: "Explain Virtual DOM and reconciliation.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are React Hooks? Name a few built-in hooks.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain useState and its usage.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain useEffect and its lifecycle equivalents.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is useContext? How does it help in state management?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does React Router work? Describe the basic components.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the key prop and why is it important in lists?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you optimize performance in React? (React.memo, useMemo, useCallback)", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain lifting state up.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are controlled and uncontrolled components?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        // Hard
        { question: "Explain React.memo in depth. When would you avoid it?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What is the React Fiber architecture and how does it improve performance?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Explain closures in the context of React hooks (stale closures in useEffect).", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How would you implement a custom hook for data fetching with loading, error, and caching?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Explain the rules of hooks and why they are enforced.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are higher-order components (HOC) and render props? Compare with hooks.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How does React handle error boundaries? Write a simple error boundary component.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Describe the steps you would take to migrate a large class-based app to hooks.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How does concurrent mode / React 18 features like useTransition improve UX?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are server components in React? What problems do they solve?", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    javascript: [
        // Easy
        { question: "What is JavaScript?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are the data types in JavaScript?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Difference between == and ===?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is a variable? How to declare one?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is an array? Give an example.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is a function? How to define one?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        // Medium
        { question: "Difference between var, let and const?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain closures in JavaScript with an example.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is event delegation and how does it work?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the concept of hoisting.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are promises? How do they differ from callbacks?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain async/await and how it simplifies asynchronous code.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the event loop? Explain the call stack, microtask queue, and macrotask queue.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain this keyword and how its binding works.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is prototypal inheritance?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        // Hard
        { question: "Explain the difference between null and undefined in depth.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are generators and iterators? Provide a real-world use case.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Explain the module pattern and ES6 modules vs CommonJS.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are WeakMap and WeakSet? When would you use them?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Implement a debounce function and explain how it works.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Explain how JavaScript engines optimize code (JIT compilation, hidden classes).", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Describe the differences between apply, call, and bind with examples.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are Proxies in JavaScript? Provide a practical use case.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Explain memory leaks in JavaScript and how to avoid them.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How would you implement a simple Promise from scratch?", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    node: [
        { question: "What is Node.js and what is it used for?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How do you create a simple HTTP server in Node?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is npm?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Explain the difference between readFileSync and readFile.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the Event Loop in Node.js?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are streams in Node.js? Types of streams?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does middleware work in Express?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the purpose of package.json and package-lock.json.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is the difference between process.nextTick() and setImmediate()?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How do you handle errors in Node.js?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the cluster module and how it improves performance.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What is the purpose of the buffer class?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does JWT authentication work in a Node.js API?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is CORS and how do you handle it in Express?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the difference between process.env and dotenv.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are child processes in Node.js? When to use fork vs spawn?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How would you implement rate limiting in an Express app?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the role of the event emitter.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are the performance implications of using synchronous code in Node?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Describe a strategy for handling unhandled promise rejections.", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    java: [
        { question: "What is Java? What are its key features?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Explain JVM, JRE, and JDK.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Difference between abstract class and interface.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are the four principles of OOP? Explain each briefly.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is method overloading vs overriding?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain exception handling in Java.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are collections? List vs Set vs Map.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How does garbage collection work in Java?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What is multithreading? How to create a thread?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the synchronized keyword and its alternatives.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are Java streams? How do they differ from collections?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the difference between final, finally, and finalize.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the Java Memory Model? Describe heap and stack.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How do you connect to a database using JDBC?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the significance of equals() and hashCode() contracts.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are annotations in Java? Provide examples.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the difference between checked and unchecked exceptions?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the Singleton design pattern and its thread-safe implementation.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are lambda expressions and functional interfaces?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does Spring framework simplify enterprise development?", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    python: [
        { question: "What is Python? What are its main use cases?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Difference between list and tuple.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are decorators in Python? Provide an example.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain how memory management works in Python.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the Global Interpreter Lock (GIL)?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How do you handle exceptions in Python?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is the difference between deep copy and shallow copy?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain generators and the yield keyword.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are list comprehensions? Give examples.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How does Python's garbage collector work?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are *args and **kwargs?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the difference between @staticmethod and @classmethod.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the purpose of __init__ and __str__ methods?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How do you manage packages and dependencies in Python?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are context managers? How do you create one?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the differences between Python 2 and Python 3.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the map(), filter(), and reduce() functions?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you write unit tests in Python?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the asyncio library? How does it enable asynchronous programming?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Explain metaclasses in Python.", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    php: [
        { question: "What is PHP and what is it commonly used for?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How do you embed PHP code in HTML?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are the differences between GET and POST methods?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are sessions in PHP? How do they work?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is Composer and why is it important?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the difference between include and require.", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is the use of the double arrow operator (=>) in PHP?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you prevent SQL injection in PHP?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are traits in PHP? How do they differ from interfaces?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the MVC pattern in a typical PHP framework like Laravel.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What is PDO and how does it improve database access?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you handle file uploads in PHP?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the difference between abstract class and interface in PHP?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are namespaces in PHP?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain how error handling works in PHP.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the purpose of the .htaccess file in PHP applications?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Describe the difference between cookies and sessions.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is Laravel? Name some of its key features.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does dependency injection work in PHP frameworks?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are PHP closures and how do they interact with $this?", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    typescript: [
        { question: "What is TypeScript and how does it differ from JavaScript?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What are the basic types in TypeScript?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is an interface? How is it different from a type?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain generics in TypeScript with an example.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are enums and when would you use them?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does type narrowing work?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the difference between any, unknown, and never?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "Explain how decorators work in TypeScript.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are mapped types and conditional types? Provide examples.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How do you configure TypeScript for a large project?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the role of tsconfig.json?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How do you use utility types like Pick, Omit, Partial, Required?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the difference between type assertion and type declaration.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are declaration files (.d.ts) and when do you need them?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you type a higher-order function?", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    nextjs: [
        { question: "What is Next.js and what problems does it solve?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Explain the difference between server-side rendering (SSR) and static site generation (SSG).", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the pages directory convention in Next.js?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How does routing work in Next.js? (file-based routing)", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is getServerSideProps and when should you use it?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is getStaticProps and getStaticPaths?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you handle API routes in Next.js?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain incremental static regeneration (ISR).", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How does Next.js optimize images? (next/image)", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is Middleware in Next.js 12+?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How do you implement authentication in Next.js?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the purpose of _app.js and _document.js?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How would you deploy a Next.js app to Vercel?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Explain how code splitting works automatically in Next.js.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are the advantages of using the new app directory (Next.js 13+)?", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    mongodb: [
        { question: "What is MongoDB and how does it differ from relational databases?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is a document in MongoDB? What is a collection?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Explain indexing in MongoDB. Why is it important?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you perform CRUD operations in MongoDB?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is the aggregation pipeline? Give an example.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What are embedded documents and when would you use them?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain sharding in MongoDB.", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How does replication work in MongoDB? (replica sets)", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the difference between MongoDB and Mongoose?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How do you design a schema for a many-to-many relationship in MongoDB?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the different types of indexes in MongoDB (single field, compound, text, 2dsphere).", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the $lookup stage in aggregation? How does it work?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How would you improve the performance of a slow MongoDB query?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are transactions in MongoDB? When are they necessary?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How do you handle schema validation in MongoDB?", questionType: "technical", difficulty: "medium", maxScore: 75 },
    ],

    docker: [
        { question: "What is Docker and why is it used?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "What is a container? How does it differ from a virtual machine?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is a Dockerfile? Describe its common instructions.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the difference between CMD and ENTRYPOINT?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you use docker-compose? Give an example.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is a volume in Docker? Why would you use it?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain the purpose of Docker networks.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How do you optimize Docker images for size?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What is the difference between EXPOSE and publish ports (-p)?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does layer caching work in Docker builds?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "What are multi-stage builds? When would you use them?", questionType: "technical", difficulty: "hard", maxScore: 100 },
        { question: "How do you share data between containers?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the difference between a Docker image and a container?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "How would you debug a container that is failing to start?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "Explain Docker Swarm vs Kubernetes at a high level.", questionType: "technical", difficulty: "hard", maxScore: 100 },
    ],

    generic: [
        // Behavioral
        { question: "Tell me about yourself.", questionType: "behavioral", difficulty: "easy", maxScore: 50 },
        { question: "What are your greatest strengths?", questionType: "behavioral", difficulty: "easy", maxScore: 50 },
        { question: "What is your biggest weakness?", questionType: "behavioral", difficulty: "easy", maxScore: 50 },
        { question: "Why do you want to work here?", questionType: "behavioral", difficulty: "easy", maxScore: 50 },
        { question: "Where do you see yourself in 5 years?", questionType: "behavioral", difficulty: "easy", maxScore: 50 },
        { question: "Describe a challenging project you worked on and how you overcame obstacles.", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "Tell me about a time you had a conflict with a colleague and how you resolved it.", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "How do you handle tight deadlines?", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "Give an example of a time you demonstrated leadership skills.", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "Describe a situation where you had to learn a new technology quickly.", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "How do you prioritize your work when you have multiple tasks?", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "Tell me about a mistake you made and how you fixed it.", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "What is your approach to giving and receiving feedback?", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        { question: "Why should we hire you?", questionType: "behavioral", difficulty: "easy", maxScore: 50 },
        { question: "How do you stay updated with industry trends?", questionType: "behavioral", difficulty: "medium", maxScore: 75 },
        // Technical mixed
        { question: "Explain the difference between SQL and NoSQL databases.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is REST? What are its principles?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is Git and why is it important?", questionType: "technical", difficulty: "easy", maxScore: 50 },
        { question: "Explain the difference between functional and object-oriented programming.", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is CI/CD and how does it improve development?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "What is the difference between unit testing and integration testing?", questionType: "technical", difficulty: "medium", maxScore: 75 },
        { question: "How does the internet work? (DNS, HTTP, browser rendering)", questionType: "technical", difficulty: "medium", maxScore: 75 },
    ],
};